# Generated by Django 5.0.14 on 2026-07-17 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='break_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='attendance',
            name='captured_image',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_photos/'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_worked_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('check_in_time', models.TimeField()),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('captured_image', models.ImageField(blank=True, null=True, upload_to='attendance_photos/')),
                ('check_in_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_in_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_in_accuracy', models.FloatField(blank=True, null=True)),
                ('check_in_address', models.TextField(blank=True, null=True)),
                ('check_in_device_info', models.CharField(blank=True, max_length=255, null=True)),
                ('check_out_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_accuracy', models.FloatField(blank=True, null=True)),
                ('check_out_address', models.TextField(blank=True, null=True)),
                ('check_out_device_info', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='attendance.attendance')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
