# Generated by Django 5.0.14 on 2026-07-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_break_hours_attendance_captured_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='check_out_captured_image',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_photos/'),
        ),
    ]
