# Generated by Django 5.0.14 on 2026-07-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendancesession_auto_checkout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='checkout_missed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='continue_clicked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='continue_shift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='ot_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='ot_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
