# Generated by Django 5.0.14 on 2026-07-18 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_attendancesession_out_of_office_since_locationping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancesession',
            options={'ordering': ['check_in_time']},
        ),
        migrations.CreateModel(
            name='AttendanceCorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('request_type', models.CharField(choices=[('MISSED_IN', 'Missed Check In'), ('MISSED_OUT', 'Missed Check Out'), ('MISSED_BOTH', 'Missed Both Check In & Check Out'), ('CONTINUE_SHIFT', 'Continue Shift Approval'), ('OT_APPROVAL', 'Overtime Approval'), ('LATE_CHECKIN_WHILE_ACTIVE', 'Check In After Shift Ended')], max_length=40)),
                ('reason', models.TextField()),
                ('requested_check_in', models.TimeField(blank=True, null=True)),
                ('requested_check_out', models.TimeField(blank=True, null=True)),
                ('check_in_photo', models.ImageField(blank=True, null=True, upload_to='correction_photos/')),
                ('check_out_photo', models.ImageField(blank=True, null=True, upload_to='correction_photos/')),
                ('location_address', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='correction_attachments/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('rejected_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_corrections', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_corrections', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correction_requests', to='attendance.attendancesession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
