# Generated by Django 5.0.14 on 2026-07-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_alter_attendancesession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='pre_continue_approved',
            field=models.BooleanField(default=False),
        ),
    ]
