# Generated by Django 5.0.14 on 2026-07-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leaverequest_is_paid_alter_leavebalance_leave_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='custom_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='duration_type',
            field=models.CharField(choices=[('full_day', 'Full Day'), ('half_day', 'Half Day'), ('custom_hours', 'Custom Hours')], default='full_day', max_length=20),
        ),
    ]
