# Generated by Django 5.0.14 on 2026-07-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeeprofile_pf_deduction_employeeprofile_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='allowed_leaves',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='used_leaves',
            field=models.IntegerField(default=0),
        ),
    ]
