# Generated by Django 5.0.14 on 2026-07-17 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_firm'),
        ('employee', '0003_employeeprofile_allowed_leaves_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='pf_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat Amount'), ('disabled', 'Disabled')], default='disabled', max_length=20),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='pf_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='EmployeeFirmAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pf_type', models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat Amount'), ('disabled', 'Disabled')], default='disabled', max_length=20)),
                ('pf_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firm_allocations', to='employee.employeeprofile')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_allocations', to='company.firm')),
            ],
            options={
                'unique_together': {('employee_profile', 'firm')},
            },
        ),
    ]
