# Generated by Django 5.0.14 on 2026-07-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employeeprofile_pf_type_employeeprofile_pf_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='checkout_missed_count',
            field=models.IntegerField(default=0),
        ),
    ]
