# Generated by Django 5.0.14 on 2026-07-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employeeprofile_checkout_missed_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='work_category',
            field=models.CharField(choices=[('OFFICE', 'Office Staff'), ('FIELD', 'Field Staff')], default='OFFICE', max_length=20),
        ),
    ]
