# Generated by Django 5.0.14 on 2026-07-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employeeprofile_work_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='missed_checkin_count',
            field=models.IntegerField(default=0),
        ),
    ]
