# Generated by Django 5.0.14 on 2026-07-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_firm'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='geofence_grace_period_minutes',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='company',
            name='location_update_frequency_minutes',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='company',
            name='office_radius_meters',
            field=models.IntegerField(default=100),
        ),
    ]
