# Generated by Django 5.0.14 on 2026-07-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_latitude_company_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='full_day_hours',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='company',
            name='half_day_hours',
            field=models.DecimalField(decimal_places=2, default=4.0, max_digits=4),
        ),
    ]
