# Generated by Django 5.0.14 on 2026-07-05 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Fully Repaid')], default='PENDING', max_length=20)),
                ('monthly_deduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('repaid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_advances', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_salaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('worked_days', models.IntegerField(default=0)),
                ('absent_days', models.IntegerField(default=0)),
                ('unpaid_leaves', models.IntegerField(default=0)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('advance_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unpaid_leave_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('absent_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('PAID', 'Paid')], default='DRAFT', max_length=20)),
                ('payslip_pdf_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
