# Generated by Django 5.0.14 on 2026-07-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='pf_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
