# Generated by Django 5.0.14 on 2026-07-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payroll_pf_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='already_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='advancesalary',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('DISBURSED', 'Disbursed/Paid'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Fully Repaid')], default='PENDING', max_length=20),
        ),
    ]
