# Generated by Django 5.0.14 on 2026-07-17 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_firm'),
        ('payroll', '0003_payroll_already_paid_payroll_bonus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollBranchBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pf_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_distributions', to='company.firm')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_distributions', to='payroll.payroll')),
            ],
            options={
                'unique_together': {('payroll', 'firm')},
            },
        ),
    ]
