# Generated by Django 5.0.14 on 2026-07-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payrollbranchbreakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollbranchbreakdown',
            name='absent_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollbranchbreakdown',
            name='advance_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollbranchbreakdown',
            name='unpaid_leave_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
