# Generated by Django 5.0.14 on 2026-07-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='postpone_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
